version: "3.9"

services:
  postgres:
    image: postgres:15
    container_name: transaction-postgres
    environment:
      POSTGRES_DB: transaction_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: "@nive1010"
    ports:
      - "5432:5432"
    networks:
      - transaction-net

  app:
    image: transaction-system
    container_name: transaction-app
    depends_on:
      - postgres
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/transaction_db
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: "@nive1010"
    ports:
      - "8080:8080"
    networks:
      - transaction-net

networks:
  transaction-net:
